export const data = [
  {
    id: 1,
    title: "Modern Laptop",
    description: "Sleek modern laptop on a wooden desk.",
    price: 799.99,
    category: "Electronics",
    image_url: "https://picsum.photos/id/1/500/400",
  },
  {
    id: 2,
    title: "Headphones with Mic",
    description: "Black over-ear headphones with a mic.",
    price: 59.99,
    category: "Audio",
    image_url: "https://picsum.photos/id/10/500/400",
  },
  {
    id: 3,
    title: "Smartwatch",
    description: "Smartwatch showing digital time.",
    price: 199.99,
    category: "Wearables",
    image_url: "https://picsum.photos/id/20/500/400",
  },
  {
    id: 4,
    title: "Professional Camera",
    description: "DSLR camera on a table.",
    price: 549.99,
    category: "Cameras",
    image_url: "https://picsum.photos/id/30/500/400",
  },
  {
    id: 5,
    title: "Gaming Mouse",
    description: "RGB gaming mouse with ergonomic design.",
    price: 39.99,
    category: "Computer Peripherals",
    image_url: "https://picsum.photos/id/40/500/400",
  },
  {
    id: 6,
    title: "Mechanical Keyboard",
    description: "Mechanical keyboard with backlit keys.",
    price: 89.99,
    category: "Computer Peripherals",
    image_url: "https://picsum.photos/id/50/500/400",
  },
  {
    id: 7,
    title: "4K Monitor",
    description: "Ultra HD 4K monitor on a clean desk.",
    price: 329.99,
    category: "Computers",
    image_url: "https://picsum.photos/id/60/500/400",
  },
  {
    id: 8,
    title: "Portable Power Bank",
    description: "High-capacity power bank.",
    price: 49.99,
    category: "Accessories",
    image_url: "https://picsum.photos/id/70/500/400",
  },
  {
    id: 9,
    title: "Bluetooth Speaker",
    description: "Portable bluetooth speaker.",
    price: 29.99,
    category: "Audio",
    image_url: "https://picsum.photos/id/80/500/400",
  },
  {
    id: 10,
    title: "Smartphone",
    description: "Slim smartphone.",
    price: 499.99,
    category: "Electronics",
    image_url: "https://picsum.photos/id/90/500/400",
  },

  {
    id: 11,
    title: "Tablet on Table",
    description: "Tablet device on table.",
    price: 229.99,
    category: "Electronics",
    image_url: "https://picsum.photos/id/100/500/400",
  },
  {
    id: 12,
    title: "AirPods Case",
    description: "Wireless earbuds case.",
    price: 19.99,
    category: "Audio",
    image_url: "https://picsum.photos/id/110/500/400",
  },
  {
    id: 13,
    title: "Fitness Tracker Band",
    description: "Slim fitness tracker.",
    price: 69.99,
    category: "Wearables",
    image_url: "https://picsum.photos/id/120/500/400",
  },
  {
    id: 14,
    title: "Coffee Maker",
    description: "Modern coffee maker.",
    price: 129.99,
    category: "Kitchen",
    image_url: "https://picsum.photos/id/130/500/400",
  },
  {
    id: 15,
    title: "Air Fryer",
    description: "Digital air fryer.",
    price: 79.99,
    category: "Kitchen",
    image_url: "https://picsum.photos/id/140/500/400",
  },
  {
    id: 16,
    title: "Yoga Mat",
    description: "Non-slip yoga mat.",
    price: 24.99,
    category: "Fitness",
    image_url: "https://picsum.photos/id/150/500/400",
  },
  {
    id: 17,
    title: "Dumbbell Set",
    description: "Adjustable dumbbells.",
    price: 89.99,
    category: "Fitness",
    image_url: "https://picsum.photos/id/160/500/400",
  },
  {
    id: 18,
    title: "Running Shoes",
    description: "Lightweight shoes.",
    price: 59.99,
    category: "Footwear",
    image_url: "https://picsum.photos/id/170/500/400",
  },
  {
    id: 19,
    title: "Leather Wallet",
    description: "Genuine leather wallet.",
    price: 39.99,
    category: "Accessories",
    image_url: "https://picsum.photos/id/180/500/400",
  },
  {
    id: 20,
    title: "Sunglasses",
    description: "Stylish sunglasses.",
    price: 24.99,
    category: "Accessories",
    image_url: "https://picsum.photos/id/190/500/400",
  },

  {
    id: 21,
    title: "Backpack",
    description: "Durable travel backpack.",
    price: 49.99,
    category: "Bags",
    image_url: "https://picsum.photos/id/200/500/400",
  },
  {
    id: 22,
    title: "Electric Toothbrush",
    description: "Rechargeable toothbrush.",
    price: 39.99,
    category: "Personal Care",
    image_url: "https://picsum.photos/id/210/500/400",
  },
  {
    id: 23,
    title: "Hair Dryer",
    description: "Compact hair dryer.",
    price: 49.99,
    category: "Personal Care",
    image_url: "https://picsum.photos/id/220/500/400",
  },
  {
    id: 24,
    title: "Digital Alarm Clock",
    description: "LED alarm clock.",
    price: 19.99,
    category: "Home",
    image_url: "https://picsum.photos/id/230/500/400",
  },
  {
    id: 25,
    title: "Smart Light Bulb",
    description: "Color-changing bulb.",
    price: 14.99,
    category: "Home Automation",
    image_url: "https://picsum.photos/id/240/500/400",
  },
  {
    id: 26,
    title: "Electric Kettle",
    description: "Stainless steel kettle.",
    price: 39.99,
    category: "Kitchen",
    image_url: "https://picsum.photos/id/250/500/400",
  },
  {
    id: 27,
    title: "Blender",
    description: "High-speed blender.",
    price: 59.99,
    category: "Kitchen",
    image_url: "https://picsum.photos/id/260/500/400",
  },
  {
    id: 28,
    title: "Office Chair",
    description: "Ergonomic office chair.",
    price: 129.99,
    category: "Furniture",
    image_url: "https://picsum.photos/id/270/500/400",
  },
  {
    id: 29,
    title: "Gaming Desk",
    description: "Desk with LED lights.",
    price: 109.99,
    category: "Furniture",
    image_url: "https://picsum.photos/id/280/500/400",
  },
  {
    id: 30,
    title: "Outdoor Tent",
    description: "Camping tent.",
    price: 149.99,
    category: "Outdoor",
    image_url: "https://picsum.photos/id/290/500/400",
  },

  {
    id: 31,
    title: "Mountain Bike",
    description: "Mountain bike.",
    price: 299.99,
    category: "Sports",
    image_url: "https://picsum.photos/id/300/500/400",
  },
  {
    id: 32,
    title: "Yoga Block",
    description: "Foam yoga block.",
    price: 9.99,
    category: "Fitness",
    image_url: "https://picsum.photos/id/310/500/400",
  },
  {
    id: 33,
    title: "Water Bottle",
    description: "Steel water bottle.",
    price: 19.99,
    category: "Fitness",
    image_url: "https://picsum.photos/id/320/500/400",
  },
  {
    id: 34,
    title: "Robot Vacuum",
    description: "Smart robot vacuum.",
    price: 249.99,
    category: "Home Appliances",
    image_url: "https://picsum.photos/id/330/500/400",
  },
  {
    id: 35,
    title: "Drone",
    description: "Quadcopter drone.",
    price: 399.99,
    category: "Gadgets",
    image_url: "https://picsum.photos/id/340/500/400",
  },
  {
    id: 36,
    title: "Gaming Console Controller",
    description: "Gamepad controller.",
    price: 49.99,
    category: "Gaming",
    image_url: "https://picsum.photos/id/350/500/400",
  },
  {
    id: 37,
    title: "Electric Scooter",
    description: "Foldable scooter.",
    price: 299.99,
    category: "Gadgets",
    image_url: "https://picsum.photos/id/360/500/400",
  },
  {
    id: 38,
    title: "Smart Doorbell",
    description: "Video doorbell.",
    price: 99.99,
    category: "Home Security",
    image_url: "https://picsum.photos/id/370/500/400",
  },
  {
    id: 39,
    title: "Robot Lawn Mower",
    description: "Automatic lawn mower.",
    price: 799.99,
    category: "Garden",
    image_url: "https://picsum.photos/id/380/500/400",
  },
  {
    id: 40,
    title: "Graphic Tablet",
    description: "Drawing tablet.",
    price: 69.99,
    category: "Computers",
    image_url: "https://picsum.photos/id/390/500/400",
  },

  {
    id: 41,
    title: "Wireless Charger",
    description: "Qi charger pad.",
    price: 24.99,
    category: "Accessories",
    image_url: "https://picsum.photos/id/400/500/400",
  },
  {
    id: 42,
    title: "Laptop Sleeve",
    description: "Minimalist sleeve.",
    price: 19.99,
    category: "Bags",
    image_url: "https://picsum.photos/id/410/500/400",
  },
  {
    id: 43,
    title: "Tripod",
    description: "Camera tripod.",
    price: 29.99,
    category: "Cameras",
    image_url: "https://picsum.photos/id/420/500/400",
  },
  {
    id: 44,
    title: "SD Card",
    description: "128GB SD card.",
    price: 19.99,
    category: "Storage",
    image_url: "https://picsum.photos/id/430/500/400",
  },
  {
    id: 45,
    title: "Mini Projector",
    description: "Portable projector.",
    price: 139.99,
    category: "Electronics",
    image_url: "https://picsum.photos/id/440/500/400",
  },
  {
    id: 46,
    title: "Electric Drill",
    description: "Cordless drill.",
    price: 99.99,
    category: "Tools",
    image_url: "https://picsum.photos/id/450/500/400",
  },
  {
    id: 47,
    title: "Desk Lamp",
    description: "Adjustable lamp.",
    price: 34.99,
    category: "Lighting",
    image_url: "https://picsum.photos/id/460/500/400",
  },
  {
    id: 48,
    title: "Cookbook",
    description: "Recipe cookbook.",
    price: 24.99,
    category: "Books",
    image_url: "https://picsum.photos/id/470/500/400",
  },
  {
    id: 49,
    title: "Back Pack Hiking",
    description: "Hiking backpack.",
    price: 69.99,
    category: "Outdoor",
    image_url: "https://picsum.photos/id/480/500/400",
  },
  {
    id: 50,
    title: "Ski Goggles",
    description: "Snow ski goggles.",
    price: 89.99,
    category: "Sports",
    image_url: "https://picsum.photos/id/490/500/400",
  },
];
